### ISSUE TITLE
Fix read/write for checkins

### ISSUE THREAD

**Issue by pietercolpaert** [oSoc14/hyperRail#12]
## The problem

Right now, only GET is used for the digital travel agenda, aka the checkins.
## Understanding HTTP: the protocol of the Web

URIs on the Web are identifiers of things or "resources". They are not actions. This is because the "actions" your do on a certain resource are already defined within the HTTP protocol: GET, POST, PUT, DELETE (and maybe some others such as PATCH and HEAD). The specification of the HTTP protocol, which is implemented by HTTP clients such as browsers or libraries within application frameworks know this protocol and use its features, such as: when a GET happens, you might cache it if it is requested twice within a certain time interval. POST however can never be cached, because this is a write action and the response will depend on what exactly you've POST-ed.
## Applied on this problem

https://irail.be/checkins is the URI which identifies the travel agenda.

When you GET it when providing a token*, there are 2 possibilities:
- You will **accept HTML** as you're a browser: HTML/JS gets returned. The JS logic will request the same URL again, but this time, we're only accepting JSON.
- You **accept JSON** as you're a machine: the response will give you a JSON which contains all your check-ins. Each check-in as well is identified using a URI the server chooses. E.g., the server could have chosen http://irail.be/checkins/http%3A%2F%2Firail.be%2Fstations%2FNMBS%2F008892007%2Fdepartures%2F201407171846595e7d0e11f910903305ea4ea5e86179 (I like this URI design (yet, feel free to suggest something else) as you could use this URI as well for another user and provide some clientside features such as: if not yet checked in, provide a button to check in, if already checked in, show all the check-ins and highlight the one.).

When you POST towards https://irail.be/checkins, you should provide a body such as this one (of course, don't forget to put the content-type to application/json if you provide this in JSON):

``` JSON
{
   "departure" : "http://irail.be/stations/NMBS/008892007/departures/201407171846595e7d0e11f910903305ea4ea5e86179"
}
```

The response to this will be a `303 See Other` including a HTTP header: `Location: {uri_to_new_resource}`. This URI can be chosen by the server. I would suggest that you let the server add `url_encode('https://irail.be/stations/NMBS/008892007/departures/201407171846595e7d0e11f910903305ea4ea5e86179')` to the checkins URI. When GET-ing this URI (which will happen automatically after you've POSTed because of your HTTP client), you will get the update of the JSON of all your check-ins. You can read more about this design pattern here: https://en.wikipedia.org/wiki/Post/Redirect/Get.

Deleting a check-in has now become really easy. You just perform a DELETE over here: https://irail.be/checkins/http%3A%2F%2Firail.be%2Fstations%2FNMBS%2F008892007%2Fdepartures%2F201407171846595e7d0e11f910903305ea4ea5e86179 and you're done.

*Tokens vs. cookies must reads:
- https://auth0.com/blog/2014/01/27/ten-things-you-should-know-about-tokens-and-cookies/
- https://auth0.com/blog/2014/01/07/angularjs-authentication-with-cookies-vs-token/

**Comment by samhendrickx** [comment]
Thanks for the crash course
fixed them all
